apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres;Port=5432;Database=fcg_catalog_db;Username=catalog;Password=catalogpw"
  Jwt__Key: "CHANGE-ME-VERY-LONG-SECRET-KEY-AT-LEAST-32-CHARS"
  RabbitMq__Password: guest
